hmLoadTopic({
hmKeywords:"Battery charging",
hmTitle:"Battery charging",
hmDescription:"To charge the battery: plug the USB cable to the connector located at the end of the device ([14] in the general view); plug the USB cable to the connector of a computer or a...",
hmPrevLink:"sound_indication.html",
hmNextLink:"firmwareupdate.html",
hmParentLink:"standalone_use.html",
hmBreadCrumbs:"<a href=\"standalone_use.html\">Stand-alone use of the device<\/a>",
hmTitlePath:"Stand-alone use of the device > Battery charging",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Battery charging<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">To charge the battery:<\/p>\n\r<p style=\"text-align: left; text-indent: 0px; padding: 0px 0px 0px 0.8125rem; margin: 0px 0px 0px 0px;\"><span style=\"font-size:1.00rem; font-family: \'Arial Unicode MS\',\'Lucida Sans Unicode\',\'Arial\';color:#000000;display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>plug the USB cable to the connector located at the end of the device ([14] in the <a href=\"device_construction.html\" class=\"topiclink\">general view<\/a>);<\/p><p style=\"text-align: left; text-indent: 0px; padding: 0px 0px 0px 0.8125rem; margin: 0px 0px 0px 0px;\"><span style=\"font-size:1.00rem; font-family: \'Arial Unicode MS\',\'Lucida Sans Unicode\',\'Arial\';color:#000000;display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>plug the USB cable to the connector of a computer or a special charger;<\/p><p style=\"text-align: left; text-indent: 0px; padding: 0px 0px 0px 0.8125rem; margin: 0px 0px 0px 0px;\"><span style=\"font-size:1.00rem; font-family: \'Arial Unicode MS\',\'Lucida Sans Unicode\',\'Arial\';color:#000000;display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>leave the device connected to the charging source until it is fully charged.<\/p><p class=\"p_Normal\">The indicator of the activity of the charging process is the glowing of the blue indicator ([18] in the general view). If the device is turned on, then the screen displays the icon ([3] in the general view). At the end of the charging procedure, the blue indicator will turn off and the icon will change to the sign of power supply from an external source.<\/p>\n\r<p class=\"p_Normal\">Pay attention to the charge indicator icon while using the device. If the charge indicator is empty <img alt=\"battery_empty_sym\" style=\"margin:0;width:1.3750rem;height:0.8750rem;border:none\" src=\".\/images\/battery_empty_sym.png\"\/>, then connect the device to the charger.<\/p>\n\r<p class=\"p_Normal\">In order to ensure correct battery charging conditions and increase battery life, the dosimeter is designed to block the battery charging process when the instrument temperature is above +40°C or below 0°C.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><span style=\"font-style: italic; font-weight: bold; color: #ff0000;\">Attention! Use only dedicated chargers or a computer USB port to charge the device. Connecting the device to the wrong charging source may damage it. A device damaged as a result of improper charging is not eligible for warranty repair.<\/span><br \/>\n\r<span style=\"font-style: italic; font-weight: bold; color: #ff0000;\">If the battery is completely discharged, the instrument may not respond to attempts to turn on. To start the dosimeter, the battery must be recharged. Then disconnect the cable and reconnect it. The device will be ready for operation.<\/span><\/p>\n\r"
})
