hmLoadTopic({
hmKeywords:"",
hmTitle:"Display Modes",
hmDescription:"The Radiacode-10X series dosimeter has a single mode of operation - continuous data collection, accumulation and analysis.",
hmPrevLink:"reset_to_factory_defaults.html",
hmNextLink:"spectrum.html",
hmParentLink:"standalone_use.html",
hmBreadCrumbs:"<a href=\"standalone_use.html\">Stand-alone use of the device<\/a>",
hmTitlePath:"Stand-alone use of the device > Display Modes",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Display Modes<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">The Radiacode-10X series dosimeter has a single mode of operation - continuous data collection, accumulation and analysis.<\/p>\n\r<p class=\"p_Normal\">At any moment one of several ways of displaying the radiation situation assessment is available:<\/p>\n\r<p style=\"line-height: 1.28; margin: 0px 0px 0.6875rem 0px;\"><span style=\"color: #000000;\">&nbsp;<\/span><\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0px 0px 0px 1.7500rem;\"><img alt=\"spectrum_sym\" style=\"margin:0;width:2.0000rem;height:1.7500rem;border:none\" src=\".\/images\/spectrum_sym.png\"\/> &nbsp; &nbsp; &nbsp; &nbsp;<a href=\"spectrum.html\" class=\"topiclink\">Spectrum<\/a> <span style=\"font-size: 1.20rem; font-family: \'Times New Roman\',Times,Georgia,serif;\">–<\/span> &nbsp;energy spectrum of photon radiation;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0px 0px 0px 1.7500rem;\"><img alt=\"dose_rate_sym\" style=\"margin:0;width:2.0000rem;height:2.0000rem;border:none\" src=\".\/images\/dose_rate_sym.png\"\/> &nbsp; &nbsp; &nbsp; &nbsp;<a href=\"dose_rate.html\" class=\"topiclink\">Monitor<\/a> <span style=\"font-size: 1.20rem; font-family: \'Times New Roman\',Times,Georgia,serif;\">– <\/span>estimation of dose rate and count rate;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0px 0px 0px 1.7500rem;\"><img alt=\"dose_sym\" style=\"margin:0;width:1.5000rem;height:1.7500rem;border:none\" src=\".\/images\/dose_sym.png\"\/> &nbsp; &nbsp; &nbsp; &nbsp;<a href=\"dose.html\" class=\"topiclink\">Dose<\/a> <span style=\"font-size: 1.20rem; font-family: \'Times New Roman\',Times,Georgia,serif;\">– <\/span>dose assessment;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0px 0px 0px 1.7500rem;\"><img alt=\"lookup_sym\" style=\"margin:0;width:2.0000rem;height:2.0000rem;border:none\" src=\".\/images\/lookup_sym.png\"\/> &nbsp; &nbsp; &nbsp; &nbsp;<a href=\"scan.html\" class=\"topiclink\">Search<\/a> <span style=\"font-size: 1.20rem; font-family: \'Times New Roman\',Times,Georgia,serif;\">–<\/span> operational search.<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0px 0px 0px 1.7500rem;\">&nbsp;<\/p>\n\r<p style=\"line-height: 1.28; margin: 0px 0px 0.6875rem 0px;\">During operation, the instrument also detects the exceeding of all <a href=\"alarms.html\" class=\"topiclink\">Alarms<\/a> levels. Informs the user of radiation hazards or changes in the environment.<\/p>\n\r"
})
