hmLoadTopic({
hmKeywords:"Stand-alone use of the device",
hmTitle:"Stand-alone use of the device",
hmDescription:"Portable dosimeter portable radiation detector  Radiacode-10X series is designed to assess the radiation situation in real time. In addition, the instrument automatically keeps...",
hmPrevLink:"safety_regulations.html",
hmNextLink:"getting_started.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Stand-alone use of the device",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Stand-alone use of the device<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">Portable dosimeter portable radiation detector &nbsp;Radiacode-10X series is designed to assess the radiation situation in real time. In addition, the instrument automatically keeps a log of measurement results and events. This makes it possible to analyze them, including with the help of standard software on a smartphone or personal computer. The dosimeter is suitable for work on the ground, with samples of construction materials, with specially selected and prepared food or soil samples.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Radiacode-10X series is designed for long-term autonomous use. Results at any moment can be presented in the form of dose rate estimation, count rate, accumulated dose, absorbed radiation energy spectrum. Assessment and accumulation of data do not depend on the change of display mode.<\/p>\n\r<p class=\"p_Normal\">The instrument allows storing the accumulated data in the internal memory up to thousand last hours of observations.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">In addition to autonomous operation portable radiation detector can be connected to a personal computer via USB cable or to an Android or iOS smartphone via Bluetooth. Connection to an Android smartphone is also possible via USB OTG. When connected to a computer or smartphone, the accumulated data are transferred to an external device, and the newly received data are transferred there immediately without being stored in the built-in memory.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">To connect the device to a computer it is necessary to<a href=\"personal_interface.html\" class=\"topiclink\"> install software <\/a>Radiacode. <br \/>\n\rThe program is available for download at <a href=\"https:\/\/space.radiacode.com\" target=\"_blank\" class=\"weblink\" title=\"https:\/\/space.radiacode.com\">https:\/\/space.radiacode.com<\/a>.<br \/>\n\rWith the help of the program Radiacode you can transfer data to a computer, view it and manage it &nbsp;portable radiation detectorом.<\/p>\n\r<p class=\"p_Normal\">For a detailed description of the program interface, see in chapter <a href=\"personal_interface.html\" class=\"topiclink\">&quot;Working with the use of a computer&quot;<\/a>.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">To work with a smartphone <a href=\"mobile_interface.html\" class=\"topiclink\">install the app on it <\/a>Radiacode, <br \/>\n\ravailable at <a href=\"https:\/\/space.radiacode.com\" target=\"_blank\" class=\"weblink\" title=\"https:\/\/space.radiacode.com\">https:\/\/space.radiacode.com<\/a> and GooglePlay, <br \/>\n\ror use the QR code:<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0px 0px 0px 12.1875rem;\"><img alt=\"QRarc101_cut\" style=\"margin:0;width:9.1875rem;height:9.1875rem;border:none\" src=\".\/images\/qrarc101_cut.png\"\/><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
