hmLoadIndex({sections:["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"],
keywords:[{kw:"Alarm",hrefs:["alarms.html"],captions:["Alarms"],subkw:[]},
{kw:"Battery charging",hrefs:["battery_charging.html"],captions:["Battery charging"],subkw:[]},
{kw:"Before use",hrefs:["getting_started.html"],captions:["Before use"],subkw:[]},
{kw:"Bluetooth",hrefs:["bluetooth_setting.html"],captions:["Bluetooth settings"],subkw:[]},
{kw:"button",hrefs:["control.html","using_the_menu.html"],captions:["Buttons","Menu usage"],subkw:[]},
{kw:"contrast",hrefs:["display.html"],captions:["Display"],subkw:[]},
{kw:"control",hrefs:["control.html"],captions:["Buttons"],subkw:[]},
{kw:"Count rate alarm",hrefs:["count_rate_alarm_thresholds.html"],captions:["Count rate - alarm levels"],subkw:[]},
{kw:"date",hrefs:["date_and_time_setting.html"],captions:["Time settings"],subkw:[]},
{kw:"Device settings",hrefs:["configuring_the_device.html"],captions:["Device settings"],subkw:[]},
{kw:"display",hrefs:["display.html"],captions:["Display"],subkw:[]},
{kw:"Dose alarm",hrefs:["dose_alarm_thresholds.html"],captions:["Dose - alarm levels"],subkw:[]},
{kw:"Dose rate alarm",hrefs:["dose_rate_alarm_thresholds.html"],captions:["Dose rate - alarm levels"],subkw:[]},
{kw:"Firmware",hrefs:["firmwareupdate.html"],captions:["Firmware update"],subkw:[]},
{kw:"Firmware update",hrefs:["firmwareupdate.html"],captions:["Firmware update"],subkw:[]},
{kw:"icons",hrefs:["icons.html"],captions:["Icons"],subkw:[]},
{kw:"info",hrefs:["device_info.html"],captions:["Device info"],subkw:[]},
{kw:"Language",hrefs:["menu_language.html"],captions:["Language selection"],subkw:[]},
{kw:"Language selection",hrefs:["menu_language.html"],captions:["Language selection"],subkw:[]},
{kw:"light",hrefs:["sound_indication.html"],captions:["Indication: sound, vibration, light"],subkw:[]},
{kw:"long press",hrefs:["control.html","using_the_menu.html"],captions:["Buttons","Menu usage"],subkw:[]},
{kw:"menu",hrefs:["using_the_menu.html"],captions:["Menu usage"],subkw:[]},
{kw:"menu usage",hrefs:["using_the_menu.html"],captions:["Menu usage"],subkw:[]},
{kw:"menu use",hrefs:["using_the_menu.html"],captions:["Menu usage"],subkw:[]},
{kw:"off",hrefs:["switchon_turnoff.html"],captions:["Turning on and off"],subkw:[]},
{kw:"on",hrefs:["switchon_turnoff.html"],captions:["Turning on and off"],subkw:[]},
{kw:"PC",hrefs:["personal_interface.html"],captions:["Work with a PC"],subkw:[]},
{kw:"pressing",hrefs:["control.html","using_the_menu.html"],captions:["Buttons","Menu usage"],subkw:[]},
{kw:"Reset",hrefs:["reset_to_factory_defaults.html"],captions:["Reset to factory settings"],subkw:[]},
{kw:"resolution",hrefs:["display.html"],captions:["Display"],subkw:[]},
{kw:"screen",hrefs:["display_settings.html"],captions:["Display settings"],subkw:[]},
{kw:"screen adjustment",hrefs:["display_settings.html"],captions:["Display settings"],subkw:[]},
{kw:"screen contrast",hrefs:["display_settings.html"],captions:["Display settings"],subkw:[]},
{kw:"screen orientation",hrefs:["display_settings.html"],captions:["Display settings"],subkw:[]},
{kw:"screen rotation",hrefs:["display_settings.html"],captions:["Display settings"],subkw:[]},
{kw:"screen setting",hrefs:["display_settings.html"],captions:["Display settings"],subkw:[]},
{kw:"short press",hrefs:["control.html","using_the_menu.html"],captions:["Buttons","Menu usage"],subkw:[]},
{kw:"smartphone",hrefs:["mobile_interface.html"],captions:["Working with a smartphone"],subkw:[]},
{kw:"sound",hrefs:["sound_indication.html"],captions:["Indication: sound, vibration, light"],subkw:[]},
{kw:"Spectrum energy",hrefs:["spectrum.html"],captions:["Spectrum"],subkw:[]},
{kw:"Stand-alone use of the device",hrefs:["standalone_use.html"],captions:["Stand-alone use of the device"],subkw:[]},
{kw:"Time",hrefs:["date_and_time_setting.html"],captions:["Time settings"],subkw:[]},
{kw:"Time settings",hrefs:["date_and_time_setting.html"],captions:["Time settings"],subkw:[]},
{kw:"vibration",hrefs:["sound_indication.html"],captions:["Indication: sound, vibration, light"],subkw:[]}]}
)
