pageinfo = [[1726486212,0,0,0,null],
	[1726486150,0,0,0,null],
	[1726486195,0,0,0,null],
	[1726486154,0,0,0,null],
	[1726486139,0,0,0,null],
	[1726486164,0,0,0,null],
	[1726486199,0,0,0,null],
	[1726486137,0,0,0,null],
	[1726486136,0,0,0,null],
	[1726486210,0,0,0,null],
	[1726486143,0,0,0,null],
	[1726486181,0,0,0,null],
	[1726486207,0,0,0,null],
	[1726486176,0,0,0,null],
	[1726486205,0,0,0,null],
	[1726486170,0,0,0,null],
	[1726486151,0,0,0,null],
	[1726486138,0,0,0,null],
	[1726486149,0,0,0,null],
	[1726486124,0,0,0,null],
	[1726486196,0,0,0,null],
	[1726486213,0,0,0,null],
	[1726486213,0,0,0,null],
	[1726486212,0,0,0,null],
	[1726486202,0,0,0,null],
	[1726486125,0,0,0,null],
	[1726486201,0,0,0,null],
	[1726486137,0,0,0,null],
	[1726486209,0,0,0,null],
	[1726486213,0,0,0,null],
	[1726486158,0,0,0,null],
	[1726486194,0,0,0,null],
	[1726486150,0,0,0,null],
	[1726486203,0,0,0,null],
	[1726486138,0,0,0,null],
	[1726486142,0,0,0,null],
	[1726486136,0,0,0,null],
	[1726486152,0,0,0,null],
	[1726486214,0,0,0,null]];
pagedata = [ ["./alarms.html","Alarms","The sources of alarms in the Radiacode-10X series device are:",""],
["./battery_charging.html","Battery charging","To charge the battery: plug the USB cable to the connector located at the end of the device ([14] in the general view); plug the USB cable to the ...",""],
["./bluetooth_setting.html","Bluetooth settings","Short press the up/down swing buttons to move the focus to [Bluetooth];",""],
["./configuring_the_device.html","Device settings","The instrument settings can be accessed from the corresponding instrument submenu –  \"Settings\".",""],
["./control.html","Buttons","Portable radiation detector  Radiacode-10X series has an intuitive menu system and is controlled by three buttons.",""],
["./count_rate_alarm_thresholds.html","Count rate - alarm levels","Briefly press the up/down rocker buttons to move the focus to [Count rate];",""],
["./date_and_time_setting.html","Time settings","When connecting Radiacode-10X series The time on the device will be set automatically when you connect it to your smartphone or computer.",""],
["./developers.html","Developer contacts","Radiacode Ltd.  3 Thalia Street, Office 222, Limassol 3011, Cyprus Тел. +357 96 207695 E-mail: support@radiacode.com Web:https://radiacode.com",""],
["./device_construction.html","Device design","Design elements, controls and indications  controls and indications portable radiation detector  Radiacode-10X series",""],
["./device_info.html","Device info","The mode is intended for presenting brief information about the device:",""],
["./display.html","Display","The instrument is equipped with a graphical monochrome display.",""],
["./display_settings.html","Display settings","You can customize the screen properties to suit your needs.",""],
["./dose.html","Dose","The mode is intended for presentation of accumulated dose.",""],
["./dose_alarm_thresholds.html","Dose - alarm levels","Briefly press the up/down rocker buttons to move the focus to [Dose];",""],
["./dose_rate.html","Monitor","This mode is intended to represent dose rate or count rate. When the instrument is turned on, it starts working in this particular display mode. A...",""],
["./dose_rate_alarm_thresholds.html","Dose rate - alarm levels","Briefly press the up/down rocker buttons to move the focus to [Dose rate];",""],
["./firmwareupdate.html","Firmware update","The device is constantly being improved and the firmware (built-in software) is regularly updated by the developer company. The current version of...",""],
["./getting_started.html","Before use","Note: If you brought the package with the device from frost to a warm room, leave it to warm up for two hours without opening. Otherwise, moisture...",""],
["./icons.html","Icons","In all display modes except settings, the display shows a logarithmic indicator:",""],
["./index.html","Introduction","This section contains the general information about dosimeter Radiacode-10X series. Later in the document, the dosimeter Radiacode-10X series is a...",""],
["./menu_language.html","Language selection","The device can support multiple languages for menus and messages.",""],
["./mobile_interface.html","Working with a smartphone","To pair with your smartphone, install the app on your smartphone Radiacode, ",""],
["./personal_interface.html","Work with a PC","To connect the device to a computer, the software must be installed Radiacode.",""],
["./possible-problems.html","Possible problems","Typical faults Possible causes Methods of elimination The device does not turn on autonomously Battery discharged Charge the battery The device op...",""],
["./presentation_mode.html","Display Modes","The Radiacode-10X series dosimeter has a single mode of operation - continuous data collection, accumulation and analysis.",""],
["./purpose_of_the_device.html","Appointment of the device","Radiacode-10X series  Portable dosimeter portable radiation detector Radiacode-10X series is designed to assess the radiation situation in re...",""],
["./reset_to_factory_defaults.html","Reset to factory settings","The menu provides an item for resetting the instrument to its original factory settings.",""],
["./safety_regulations.html","Safety precautions and warnings","Read this manual carefully before using the device.",""],
["./scan.html","Search","The mode is designed to represent the count rate in the form of a search graph. It is applicable for operative search of the source or zone with i...",""],
["./second_topic.html","Second topic","Enter topic text here.",""],
["./selection_of_units.html","Selecting units of measurement","Briefly press the up/down rocker buttons to move the focus to [Measurement units];",""],
["./signal_settings.html","Signals - sound, vibration, light","Portable radiation detector Radiacode-10X series is equipped with a combined interface for user interaction:",""],
["./sound_indication.html","Indication: sound, vibration, light","In portable radiation detectorе  Radiacode-10X series sound and vibration sources are built in to acknowledge button presses and to indicate ...",""],
["./spectrum.html","Spectrum","The mode is intended for representation of the general view of the photon (gamma and X-ray) radiation energy spectrum.",""],
["./standalone_use.html","Stand-alone use of the device","Portable dosimeter portable radiation detector  Radiacode-10X series is designed to assess the radiation situation in real time. In addition,...",""],
["./switchon_turnoff.html","Turning on and off","To include Radiacode-10X series click on round button and hold it down for three seconds.",""],
["./technicalspecifications.html","Technical specifications","General technical characteristics  Energy range of registered photon radiation (X-ray and gamma) 0.02…3 MeV Dose rate assessment: range (by C...",""],
["./using_the_menu.html","Menu usage","Let&#39;s take the state \"The device is off\" as the initial state.",""],
["./welcome_topic.html","Welcome topic","Enter topic text here.",""]];
